services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vector_app_python_prod

    environment:
      PORT: ${PORT:-3000}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_DIALECT: ${DB_DIALECT:-heatwave}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_MODEL: ${GEMINI_MODEL:-gemini-embedding-2}
      APP_USERNAME: ${APP_USERNAME:-admin}
      APP_PASSWORD: ${APP_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      RERANK_MODEL: ${RERANK_MODEL:-ms-marco-MiniLM-L-12-v2}
      RERANK_TOP_K: ${RERANK_TOP_K:-50}
    restart: always
